### ISSUE TITLE
Problem with python 2.7

### ISSUE THREAD

**Issue by ptrelease** [Skablam/flask-spawn#2]
Error installing onto Python 2.7 on Landreg/beta box:

[root@centos-python3 ~]# pip install flask-spawn
Downloading/unpacking flask-spawn
  Downloading flask-spawn-0.1.11.tar.gz
  Running setup.py (path:/tmp/pip-build-cqhWMR/flask-spawn/setup.py) egg_info for package flask-spawn

Downloading/unpacking Click (from flask-spawn)
  Downloading click-5.1-py2.py3-none-any.whl (65kB): 65kB downloaded
Downloading/unpacking Cookiecutter (from flask-spawn)
  Downloading cookiecutter-1.2.1-py2.py3-none-any.whl (43kB): 43kB downloaded
Downloading/unpacking future>=0.15.2 (from Cookiecutter->flask-spawn)
  Downloading future-0.15.2.tar.gz (1.6MB): 1.6MB downloaded
  Running setup.py (path:/tmp/pip-build-cqhWMR/future/setup.py) egg_info for package future

```
warning: no files found matching '*.au' under directory 'tests'
warning: no files found matching '*.gif' under directory 'tests'
warning: no files found matching '*.txt' under directory 'tests'
```

Requirement already satisfied (use --upgrade to upgrade): jinja2>=2.7 in /usr/lib/python2.7/site-packages (from Cookiecutter->flask-spawn)
Downloading/unpacking binaryornot>=0.2.0 (from Cookiecutter->flask-spawn)
  Downloading binaryornot-0.4.0-py2.py3-none-any.whl
Downloading/unpacking whichcraft>=0.1.1 (from Cookiecutter->flask-spawn)
  Downloading whichcraft-0.1.1-py2.py3-none-any.whl
Downloading/unpacking ruamel.yaml>=0.10.12 (from Cookiecutter->flask-spawn)
  Downloading ruamel.yaml-0.10.12.tar.gz (234kB): 234kB downloaded
  Running setup.py (path:/tmp/pip-build-cqhWMR/ruamel.yaml/setup.py) egg_info for package ruamel.yaml
    author -> Anthon van der Neut
    author_email -> a.van.der.neut@ruamel.eu
    classifiers -> ['Development Status :: 4 - Beta', 'Intended Audience :: Developers', 'License :: OSI Approved :: MIT License', 'Operating System :: OS Independent', 'Programming Language :: Python', 'Programming Language :: Python :: 2.6', 'Programming Language :: Python :: 2.7', 'Programming Language :: Python :: 3.3', 'Programming Language :: Python :: 3.4', 'Programming Language :: Python :: 3.5', 'Programming Language :: Python :: Implementation :: CPython', 'Programming Language :: Python :: Implementation :: PyPy', 'Programming Language :: Python :: Implementation :: Jython', 'Topic :: Software Development :: Libraries :: Python Modules', 'Topic :: Text Processing :: Markup']
    cmdclass -> {'install_lib': <class __main__.MyInstallLib at 0xe30ae0>}
    description -> ruamel.yaml is a YAML parser/emitter that supports roundtrip preservation of comments, seq/map flow style, and map key order
    entry_points -> None
    ext_modules -> [<setuptools.extension.Extension instance at 0x1679758>]
    install_requires -> ['ruamel.base>=1.0.0', 'ruamel.ordereddict']
    license -> MIT license
    name -> ruamel.yaml
    namespace_packages -> ['ruamel']
    package_data -> {'ruamel.yaml': ['LICENSE']}
    package_dir -> {'ruamel': '.ruamel', 'ruamel.yaml': '.'}
    packages -> ['ruamel', 'ruamel.yaml']
    url -> https://bitbucket.org/ruamel/yaml
    version -> 0.10.12

Requirement already satisfied (use --upgrade to upgrade): markupsafe in /usr/lib/python2.7/site-packages (from jinja2>=2.7->Cookiecutter->flask-spawn)
Downloading/unpacking chardet>=2.0.0 (from binaryornot>=0.2.0->Cookiecutter->flask-spawn)
  Downloading chardet-2.3.0.tar.gz (164kB): 164kB downloaded
  Running setup.py (path:/tmp/pip-build-cqhWMR/chardet/setup.py) egg_info for package chardet

```
warning: no files found matching 'COPYING'
warning: no files found matching '*.html' under directory 'docs'
warning: no files found matching '*.css' under directory 'docs'
warning: no files found matching '*.png' under directory 'docs'
warning: no files found matching '*.gif' under directory 'docs'
```

Downloading/unpacking ruamel.base>=1.0.0 (from ruamel.yaml>=0.10.12->Cookiecutter->flask-spawn)
  Downloading ruamel.base-1.0.0-py2-none-any.whl
Downloading/unpacking ruamel.ordereddict (from ruamel.yaml>=0.10.12->Cookiecutter->flask-spawn)
  Downloading ruamel.ordereddict-0.4.9.tar.gz (53kB): 53kB downloaded
  Running setup.py (path:/tmp/pip-build-cqhWMR/ruamel.ordereddict/setup.py) egg_info for package ruamel.ordereddict

Installing collected packages: flask-spawn, Click, Cookiecutter, future, binaryornot, whichcraft, ruamel.yaml, chardet, ruamel.base, ruamel.ordereddict
  Running setup.py install for flask-spawn

```
Installing spawn script to /usr/bin
```

  Running setup.py install for future

```
warning: no files found matching '*.au' under directory 'tests'
warning: no files found matching '*.gif' under directory 'tests'
warning: no files found matching '*.txt' under directory 'tests'
Installing pasteurize script to /usr/bin
Installing futurize script to /usr/bin
```

  Running setup.py install for ruamel.yaml
    author -> Anthon van der Neut
    author_email -> a.van.der.neut@ruamel.eu
    classifiers -> ['Development Status :: 4 - Beta', 'Intended Audience :: Developers', 'License :: OSI Approved :: MIT License', 'Operating System :: OS Independent', 'Programming Language :: Python', 'Programming Language :: Python :: 2.6', 'Programming Language :: Python :: 2.7', 'Programming Language :: Python :: 3.3', 'Programming Language :: Python :: 3.4', 'Programming Language :: Python :: 3.5', 'Programming Language :: Python :: Implementation :: CPython', 'Programming Language :: Python :: Implementation :: PyPy', 'Programming Language :: Python :: Implementation :: Jython', 'Topic :: Software Development :: Libraries :: Python Modules', 'Topic :: Text Processing :: Markup']
    cmdclass -> {'install_lib': <class __main__.MyInstallLib at 0x7ff11c2f0bb0>}
    description -> ruamel.yaml is a YAML parser/emitter that supports roundtrip preservation of comments, seq/map flow style, and map key order
    entry_points -> None
    ext_modules -> [<setuptools.extension.Extension instance at 0x1a13248>]
    install_requires -> ['ruamel.base>=1.0.0', 'ruamel.ordereddict']
    license -> MIT license
    name -> ruamel.yaml
    namespace_packages -> ['ruamel']
    package_data -> {'ruamel.yaml': ['LICENSE']}
    package_dir -> {'ruamel': '.ruamel', 'ruamel.yaml': '.'}
    packages -> ['ruamel', 'ruamel.yaml']
    url -> https://bitbucket.org/ruamel/yaml
    version -> 0.10.12
    building '_ruamel_yaml' extension
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.7 -c ext/_ruamel_yaml.c -o build/temp.linux-x86_64-2.7/ext/_ruamel_yaml.o
    ext/_ruamel_yaml.c:4:20: fatal error: Python.h: No such file or directory
     #include "Python.h"
                        ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-cqhWMR/ruamel.yaml/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-esftOI-record/install-record.txt --single-version-externally-managed --compile:
    author -> Anthon van der Neut

author_email -> a.van.der.neut@ruamel.eu

classifiers -> ['Development Status :: 4 - Beta', 'Intended Audience :: Developers', 'License :: OSI Approved :: MIT License', 'Operating System :: OS
Independent', 'Programming Language :: Python', 'Programming Language :: Python :: 2.6', 'Programming Language :: Python :: 2.7', 'Programming Language :: Python :: 3.3', 'Programming Language :: Python :: 3.4', 'Programming Language :: Python :: 3.5', 'Programming Language :: Python :: Implementation :: CPython', 'Programming Language :: Python :: Implementation :: PyPy', 'Programming Language :: Python :: Implementation :: Jython', 'Topic :: Software Development :: Libraries :: Python Modules', 'Topic :: Text Processing :: Markup']

cmdclass -> {'install_lib': <class __main__.MyInstallLib at 0x7ff11c2f0bb0>}

description -> ruamel.yaml is a YAML parser/emitter that supports roundtrip preservation of comments, seq/map flow style, and map key order

entry_points -> None

ext_modules -> [<setuptools.extension.Extension instance at 0x1a13248>]

install_requires -> ['ruamel.base>=1.0.0', 'ruamel.ordereddict']

license -> MIT license

name -> ruamel.yaml

namespace_packages -> ['ruamel']

package_data -> {'ruamel.yaml': ['LICENSE']}

package_dir -> {'ruamel': '.ruamel', 'ruamel.yaml': '.'}

packages -> ['ruamel', 'ruamel.yaml']

url -> https://bitbucket.org/ruamel/yaml

version -> 0.10.12

running install

running build

running build_py

creating build

creating build/lib.linux-x86_64-2.7

creating build/lib.linux-x86_64-2.7/ruamel

copying .ruamel/**init**.py -> build/lib.linux-x86_64-2.7/ruamel

creating build/lib.linux-x86_64-2.7/ruamel/yaml

copying ./scalarstring.py -> build/lib.linux-x86_64-2.7/ruamel/yaml

copying ./constructor.py -> build/lib.linux-x86_64-2.7/ruamel/yaml

copying ./compat.py -> build/lib.linux-x86_64-2.7/ruamel/yaml

copying ./emitter.py -> build/lib.linux-x86_64-2.7/ruamel/yaml

copying ./composer.py -> build/lib.linux-x86_64-2.7/ruamel/yaml

copying ./events.py -> build/lib.linux-x86_64-2.7/ruamel/yaml

copying ./setup.py -> build/lib.linux-x86_64-2.7/ruamel/yaml

copying ./representer.py -> build/lib.linux-x86_64-2.7/ruamel/yaml

copying ./**init**.py -> build/lib.linux-x86_64-2.7/ruamel/yaml

copying ./cyaml.py -> build/lib.linux-x86_64-2.7/ruamel/yaml

copying ./reader.py -> build/lib.linux-x86_64-2.7/ruamel/yaml

copying ./error.py -> build/lib.linux-x86_64-2.7/ruamel/yaml

copying ./configobjwalker.py -> build/lib.linux-x86_64-2.7/ruamel/yaml

copying ./dumper.py -> build/lib.linux-x86_64-2.7/ruamel/yaml

copying ./nodes.py -> build/lib.linux-x86_64-2.7/ruamel/yaml

copying ./resolver.py -> build/lib.linux-x86_64-2.7/ruamel/yaml

copying ./serializer.py -> build/lib.linux-x86_64-2.7/ruamel/yaml

copying ./loader.py -> build/lib.linux-x86_64-2.7/ruamel/yaml

copying ./comments.py -> build/lib.linux-x86_64-2.7/ruamel/yaml

copying ./scanner.py -> build/lib.linux-x86_64-2.7/ruamel/yaml

copying ./parser_.py -> build/lib.linux-x86_64-2.7/ruamel/yaml

copying ./tokens.py -> build/lib.linux-x86_64-2.7/ruamel/yaml

copying ./make_win_whl.py -> build/lib.linux-x86_64-2.7/ruamel/yaml

copying ./main.py -> build/lib.linux-x86_64-2.7/ruamel/yaml

copying ./LICENSE -> build/lib.linux-x86_64-2.7/ruamel/yaml

running build_ext

building '_ruamel_yaml' extension

creating build/temp.linux-x86_64-2.7

creating build/temp.linux-x86_64-2.7/ext

gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.7 -c ext/_ruamel_yaml.c -o
build/temp.linux-x86_64-2.7/ext/_ruamel_yaml.o

ext/_ruamel_yaml.c:4:20: fatal error: Python.h: No such file or directory

 #include "Python.h"

```
                ^
```

compilation terminated.

error: command 'gcc' failed with exit status 1

---

Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;**file**='/tmp/pip-build-cqhWMR/ruamel.yaml/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-esftOI-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-cqhWMR/ruamel.yaml
Storing debug log for failure in /root/.pip/pip.log

**Comment by Skablam** [comment]
You need to install the python-devel package on centos.

```
yum install -y python-devel
```
